# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
