# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmapp.Med_category'),
        ),
    ]
