# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='insurance',
            name='pharmacy',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pharmapp.Pharmacy'),
            preserve_default=False,
        ),
    ]
