# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 16:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='insurances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, null=True), size=None),
        ),
    ]
