# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pharmacy_name', models.CharField(max_length=50)),
                ('Prefered_username', models.CharField(max_length=50)),
                ('Licence_document', models.ImageField(upload_to='')),
                ('Pin_number', models.IntegerField()),
                ('Contact_name', models.CharField(max_length=50)),
                ('Contact_Email', models.EmailField(max_length=254)),
                ('Contact_phone_number', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ManyToManyField(to='pharmapp.Pharmacy'),
        ),
    ]
