# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0002_pharmacy_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=40302),
        ),
    ]
