# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmapp', '0003_auto_20190426_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='user',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='id',
            field=models.AutoField(auto_created=True, default=6, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
